#!/bin/sh

echo ----                ----
echo ---- Building model ----
echo ----                ----
php symfony propel:build-model

echo ----              ----
echo ---- Building sql ----
echo ----              ----
php symfony propel:build-sql

echo ----                ----
echo ---- Building forms ----
echo ----                ----
php symfony propel:build-forms

echo ----                  ----
echo ---- Building filters ----
echo ----                  ----
php symfony propel:build-filters

echo ----                     ----
echo ---- Recreating database ----
echo ----                     ----
php symfony propel:migrate

echo ----                  ----
echo ---- Loading fixtures ----
echo ----                  ----
php symfony propel:data-load

echo ----                    ----
echo ---- Creating superuser ----
echo ----                    ----
php symfony guard:create-user superadmin WhatCouldThePasswordPossiblyBe
php symfony guard:promote superadmin

echo ----                      ----
echo ---- Extract translations ----
echo ----                      ----
php symfony i18n:extract --auto-save --auto-delete frontend en

echo ----                    ----
echo ---- Clearing the cache ----
echo ----                    ----
php symfony cc

