<?php


/**
 * Skeleton subclass for performing query and update operations on the 'replay_category' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/12/10 22:01:19
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ReplayCategoryPeer extends BaseReplayCategoryPeer {
    const COMMON = 1;
    const PRO    = 2;
    const LOW    = 3;
    const CUP    = 4;
    const FUN    = 5;
} // ReplayCategoryPeer
