<?php


/**
 * Skeleton subclass for representing a row from the 'replay_game_type' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/10/10 22:54:28
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ReplayGameType extends BaseReplayGameType {
    public function  __toString() {
        return $this->getName();
    }
} // ReplayGameType
