<?php


/**
 * Skeleton subclass for performing query and update operations on the 'replay_game_type' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/10/10 22:54:28
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ReplayGameTypePeer extends BaseReplayGameTypePeer {

    const ONEVONE     = 1;
    const TWOVTWO     = 2;
    const THREEVTHREE = 3;
    const FOURVFOUR   = 4;
    const FFA         = 5;
    const UNKNWOWN    = 6;

    static public function getGameTypeIdByName( $name ) {
        switch($name) {
            case '1v1': return self::ONEVONE;
            case '2v2': return self::TWOVTWO;
            case '3v3': return self::THREEVTHREE;
            case '4v4': return self::FOURVFOUR;
            default   : return self::UNKNWOWN;
        }
    }
} // ReplayGameTypePeer
