<?php


/**
 * Skeleton subclass for performing query and update operations on the 'replay_oftheweek' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/20/10 23:00:53
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ReplayOftheweekPeer extends BaseReplayOftheweekPeer {

} // ReplayOftheweekPeer
