<?php


/**
 * Skeleton subclass for representing a row from the 'sf_guard_user_profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/14/10 22:11:30
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class sfGuardUserProfile extends BasesfGuardUserProfile {
    public function getAvatarPath() {
        return sfConfig::get('sf_upload_dir').'/userimg/'.$this->getAvatar();
    }

    public function getAvatarUrl() {
        return '/uploads/userimg/'.$this->getAvatar();
    }

    public function getAvatarOrDefaultUrl() {
        if (!$this->getAvatar()) {
            return sfConfig::get('app_profile_default_avatar');
        } else {
            return $this->getAvatarUrl();
        }
    }
} // sfGuardUserProfile
