dev:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=localhost;dbname=cupapp'
      username: root
      password: root
      encoding: utf8
      persistent: true
      pooling: true
prod:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=localhost;dbname='
      username: 
      password: 
      encoding: utf8
      persistent: true
      pooling: true
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=localhost;dbname=cupapp'
      username: root
      password: root
      encoding: utf8
      persistent: true
      pooling: true