generator:
  param:
    config:
      form:
        class: sfGuardUserAdminForm
        display: 
          "NONE": [username, password, password_again]
          "Permissions and groups": [is_active, is_super_admin, sf_guard_user_group_list, sf_guard_user_permission_list]
          "Details": [email, avatar, last_commented, last_uploaded]


