generator:
  class: sfPropelGenerator
  param:
    model_class:           Replay
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Replay
    plural:                Replays
    route_prefix:          replay_replayadmin
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:           [user_id, game_type_id, category_id, =description, =playersName, created_at, reported_count]
        object_actions:
          reloadReplay: ~
          _edit: ~
          _delete: ~
        batch_actions:
          reloadReplay: ~
          _delete: ~
      filter:  ~
      form:
        display: [id, user_id, game_type_id, category_id, description, download_count, reported_count, published_at, created_at, updated_at]
      edit:    ~
      new:     ~
